# Generated by Django 5.0.14 on 2026-08-18 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=200)),
                ('attached', models.CharField(blank=True, max_length=120)),
                ('attached_ref', models.CharField(blank=True, max_length=40)),
                ('owner', models.CharField(blank=True, max_length=80)),
                ('due', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('tag_class', models.CharField(choices=[('tag-accent', 'Positive'), ('tag-accent-2', 'Attention'), ('tag-outline', 'Neutral outline'), ('tag-neutral', 'Muted')], default='tag-neutral', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='crm.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='delivery.project')),
            ],
            options={
                'verbose_name_plural': 'correspondence',
                'ordering': ['order', 'item'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('attendees', models.CharField(blank=True, max_length=200)),
                ('attached_ref', models.CharField(blank=True, max_length=40)),
                ('day_label', models.CharField(default='Today', max_length=40)),
                ('minutes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='crm.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='delivery.project')),
            ],
            options={
                'ordering': ['order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('due', models.CharField(blank=True, max_length=40)),
                ('owner', models.CharField(blank=True, max_length=80)),
                ('attached_ref', models.CharField(blank=True, max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('correspondence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='secretariat.correspondence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=20, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for signature'), ('signed', 'Signed')], default='draft', max_length=10)),
                ('prepared_by', models.CharField(blank=True, max_length=80)),
                ('awaiting', models.CharField(blank=True, max_length=80)),
                ('attached_ref', models.CharField(blank=True, max_length=40)),
                ('sent_toast', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='crm.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='delivery.project')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
    ]
