# Generated by Django 5.0.14 on 2026-08-21 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(blank=True, help_text='e.g. Q3 2026', max_length=40)),
                ('kind', models.CharField(choices=[('quarterly', 'Quarterly report'), ('board', 'Board pack'), ('meeting', 'Meeting pack'), ('minutes', 'Minutes'), ('plan', 'Plan')], default='quarterly', max_length=12)),
                ('audience', models.CharField(choices=[('executive', 'Executive only'), ('company', 'Everyone'), ('finance', 'Finance and executive')], default='executive', max_length=12)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-published_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('meeting', 'Meeting'), ('review', 'Review'), ('focus', 'Focus time'), ('travel', 'Travel'), ('call', 'Call'), ('personal', 'Personal')], default='meeting', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('meta', models.CharField(blank=True, max_length=240)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('attendees', models.CharField(blank=True, max_length=240)),
                ('attached_ref', models.CharField(blank=True, max_length=40)),
                ('prepared_by', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time', 'order'],
            },
        ),
    ]
