# Generated by Django 5.0.14 on 2026-08-21 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('change_price', 'Price a change request'), ('expense', 'Approve an expense'), ('billing', 'Release a milestone for billing'), ('signature', 'Send a document for signature'), ('renewal', 'Confirm a renewal position')], default='change_price', max_length=16)),
                ('requested_by_name', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('waiting_label', models.CharField(blank=True, max_length=60)),
                ('cta', models.CharField(default='Approve', max_length=40)),
                ('target_app', models.CharField(blank=True, max_length=40)),
                ('target_model', models.CharField(blank=True, max_length=40)),
                ('target_ref', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(choices=[('pending', 'Waiting'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=300)),
                ('route', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state', 'order', '-created_at'],
            },
        ),
    ]
