# Generated by Django 5.0.14 on 2026-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billableitem',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
