# Generated by Django 5.0.14 on 2026-08-18 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('architecture', 'Architecture decisions'), ('research', 'Research findings'), ('pattern', 'Reusable patterns'), ('lesson', 'Lessons learned')], default='research', max_length=20)),
                ('meta', models.CharField(blank=True, max_length=160)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=80)),
                ('updated_label', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='crm.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='delivery.project')),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('source_project', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='delivery.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('proven_on', models.CharField(blank=True, max_length=120)),
                ('reuse_count', models.PositiveSmallIntegerField(default=0)),
                ('proposals_citing', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True)),
                ('meta', models.CharField(blank=True, max_length=160)),
                ('stage', models.CharField(choices=[('Discovery', 'Discovery'), ('Prototype', 'Prototype'), ('Testing', 'Testing'), ('Synthesis', 'Synthesis'), ('Closed', 'Closed')], default='Discovery', max_length=20)),
                ('tag_class', models.CharField(choices=[('tag-accent', 'Positive'), ('tag-accent-2', 'Attention'), ('tag-outline', 'Neutral outline'), ('tag-neutral', 'Muted')], default='tag-outline', max_length=20)),
                ('output', models.CharField(blank=True, max_length=120)),
                ('lead', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_threads', to='crm.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_threads', to='delivery.project')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('round_label', models.CharField(blank=True, max_length=40)),
                ('meta', models.CharField(blank=True, max_length=160)),
                ('sessions', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('Drafting', 'Drafting'), ('In test', 'In test'), ('Tested', 'Tested'), ('Retired', 'Retired')], default='Drafting', max_length=20)),
                ('tag_class', models.CharField(choices=[('tag-accent', 'Positive'), ('tag-accent-2', 'Attention'), ('tag-outline', 'Neutral outline'), ('tag-neutral', 'Muted')], default='tag-outline', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototypes', to='knowledge.researchthread')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
