# Generated by Django 5.0.14 on 2026-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
