# Generated by Django 5.0.14 on 2026-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_milestone_ref_alter_project_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
