# Generated by Django 5.0.14 on 2026-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_milestone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
