# Generated by Django 5.0.14 on 2026-10-01 06:35

from django.db import migrations, models


def preserve_completed_tasks(apps, schema_editor):
    apps.get_model("delivery", "Task").objects.filter(done=True).update(status="done")


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_archive_demo_data_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], db_index=True, default='todo', max_length=16),
        ),
        migrations.RunPython(preserve_completed_tasks, migrations.RunPython.noop),
    ]
