# Generated by Django 5.0.14 on 2026-09-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
