# Generated by Django 5.0.14 on 2026-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
