# Generated by Django 5.0.14 on 2026-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_changerequest_ref_alter_contract_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='list_name',
            field=models.CharField(blank=True, help_text='Name as it appears in the register', max_length=120),
        ),
    ]
