# Generated by Django 5.0.14 on 2026-08-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_organisation_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.organisation'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='crm.organisation'),
        ),
    ]
