# Generated by Django 5.0.14 on 2026-10-01 06:35

import apps.workforce.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_existing_department_heads'),
        ('delivery', '0006_task_due_date_task_priority_task_status'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('completed', models.TextField(max_length=4000)),
                ('tomorrow', models.TextField(blank=True, max_length=4000)),
                ('blockers', models.TextField(blank=True, max_length=4000)),
            ],
            options={
                'ordering': ['-date', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, storage=apps.workforce.storage.private_chat_storage, upload_to='%Y/%m'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_channel', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', '-created_at', '-id'], name='chat_history_idx'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='daily_reports', to='delivery.task'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='one_daily_report_per_person'),
        ),
    ]
