import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';
@Component({selector:'app-users-admin',standalone:true,imports:[FormsModule],template:`
<div class="workspace-page"><header class="workspace-heading"><div><p class="eyebrow">CEO / PEOPLE & ACCESS</p><h1>A team with the right access.</h1><p>Create real sign-in accounts, assign departments, and appoint department heads. Employee numbers are allocated automatically.</p></div><button class="btn btn-primary" (click)="newAccount()">New employee ＋</button></header>
@if(error()){<p role="alert" class="workspace-error">{{error()}}</p>}@if(status()){<p role="status" class="workspace-success">{{status()}}</p>}
@if(editing()) {<section class="workspace-card sage"><h2>{{form.id?'Manage employee':'Create employee account'}}</h2><form (ngSubmit)="save()"><div class="workspace-grid"><label>Full name<input name="name" [(ngModel)]="form.display_name" required maxlength="80"></label><label>Work email<input name="email" type="email" [(ngModel)]="form.email" required></label><label>Job title<input name="title" [(ngModel)]="form.job_title" maxlength="80"></label><label>{{form.id?'New password (leave blank to keep current)':'Initial password'}}<input name="password" type="password" [(ngModel)]="form.password" [required]="!form.id" minlength="8" autocomplete="new-password"></label><label>Department<select name="department" [(ngModel)]="form.department" required><option value="" disabled>Choose department</option>@for(d of setup().departments;track d.id){<option [value]="d.id">{{d.label}}</option>}</select></label><label>Role<select name="role" [(ngModel)]="form.role" required><option value="" disabled>Choose role</option>@for(r of setup().roles;track r.id){<option [value]="r.id">{{r.label}}</option>}</select></label><label>Account state<select name="state" [(ngModel)]="form.state"><option value="active">Active</option><option value="onboarding">Onboarding</option><option value="suspended">Suspended — cannot sign in</option></select></label><label class="checkbox-label"><input type="checkbox" name="head" [(ngModel)]="form.is_department_head">Head of department — can assign team work</label></div><p class="small">Share the initial password through an agreed private channel. The employee can change it in their profile.</p><div class="workspace-actions"><button class="btn btn-primary" [disabled]="busy()">{{busy()?'Saving…':'Save employee →'}}</button><button type="button" class="btn btn-secondary" (click)="editing.set(false)">Cancel</button></div></form></section>}
<section class="workspace-card"><h2>Company accounts</h2><div class="table-scroll"><table><thead><tr><th>Employee</th><th>Name & email</th><th>Role</th><th>Department head</th><th>State</th><th>Manage</th></tr></thead><tbody>@for(u of users();track u.id){<tr><td>{{u.employee_number}}</td><td><strong>{{u.display_name}}</strong><small>{{u.email}}</small></td><td>{{u.role_label}}</td><td>{{u.is_department_head?'Yes':'—'}}</td><td>{{u.state_label}}</td><td><button class="btn btn-secondary" (click)="edit(u)">Edit</button></td></tr>}@empty{<tr><td colspan="6">{{loaded()?'No accounts found.':'Loading accounts…'}}</td></tr>}</tbody></table></div></section></div>`})
export class UsersAdminComponent{
 api=inject(ApiService);users=signal<any[]>([]);setup=signal<any>({departments:[],roles:[]});editing=signal(false);busy=signal(false);loaded=signal(false);error=signal('');status=signal('');form:any={};
 constructor(){this.load();this.api.get('/workspace/setup/').subscribe({next:d=>this.setup.set(d),error:e=>this.fail(e)});}
 load(){this.users.set([]);this.page('/users/?page_size=100');}
 page(url:string){this.api.get<any>(url).subscribe({next:d=>{this.users.update(u=>[...u,...(d.results || d)]);this.loaded.set(true);if(d.next){const n=new URL(d.next,'http://localhost');this.page(n.pathname.replace(/^\/api/,'')+n.search);}},error:e=>this.fail(e)});}
 fail(e:any){this.busy.set(false);this.error.set(e.error?.detail || JSON.stringify(e.error || 'Unable to save. Try again.'));}
 newAccount(){this.form={display_name:'',email:'',password:'',job_title:'',department:'',role:'',state:'active',is_department_head:false};this.editing.set(true);this.error.set('');this.status.set('');}
 edit(u:any){this.form={...u,password:'',department:u.department||'',role:u.role||''};this.editing.set(true);this.status.set('');}
 save(){if(this.busy())return;this.busy.set(true);this.error.set('');const payload:any={};for(const k of ['display_name','email','job_title','department','role','state','is_department_head'])payload[k]=this.form[k];if(this.form.password)payload.password=this.form.password;
 const action=this.form.id?this.api.patch('/users/'+this.form.id+'/',payload):this.api.post('/users/',payload);action.subscribe({next:()=>{this.busy.set(false);this.editing.set(false);this.status.set('Employee saved. Sign-in and permissions now use this account.');this.load();},error:e=>this.fail(e)});}
}
